services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: nick 
      POSTGRES_PASSWORD: pass 
      POSTGRES_DB: trips_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nick -d trips_db"]
      interval: 3s
      timeout: 3s
      retries: 10
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: nick 
      DB_PASS: pass
      DB_NAME: trips_db
      APP_TOP_N: "10"
    volumes:
      - ./out:/out
